import { DashboardIntl } from '../../../core/i18n/translations.model';

export const dashboardIntlEn: DashboardIntl = {
  title: 'Dashboard',
  subtitle: 'Your subscriptions are under control',
  monthly: 'Per month',
  yearly: 'Per year',
  categories: 'Categories',
  topCategory: 'Top category',
  score: 'SubWise Score',
  scoreText: 'You have {count} active subscriptions. Check the advice section.',
  subscriptions: 'My subscriptions',
  trial: 'Trial',
  billedToday: 'Charges today!',
  billedTomorrow: 'Charges tomorrow!',
  billedIn: 'Charges in {days} {label}',
  billingDate: 'Billing date: {date}',
  noSubscriptions: 'You have not added any subscriptions yet.',
  addSubscriptionAction: 'Add subscription',
  manageAction: 'Manage subscription',
  manageUnavailable: 'No subscription link provided',
  deleteAction: 'Delete',
  deleteConfirmTitle: 'Delete subscription?',
  deleteConfirmDescription: 'This subscription will be removed from the list and cannot be restored.',
  deleteConfirmSubmit: 'Delete',
  searchPlaceholder: 'Search...',
  categoryAll: 'All categories',
  categorySelected: 'Selected',
  sortLabel: 'Sort',
  sortTerm: 'By billing date',
  sortPriceDesc: 'Most expensive first',
  sortPriceAsc: 'Cheapest first',
  sortName: 'Name',
};
