import { DashboardIntl } from '../../../core/i18n/translations.model';

export const dashboardIntlEs: DashboardIntl = {
  title: 'Panel',
  subtitle: 'Tus suscripciones bajo control',
  monthly: 'Por mes',
  yearly: 'Por ano',
  categories: 'Categorias',
  topCategory: 'Categoria principal',
  score: 'Puntuacion SubWise',
  scoreText: 'Tienes {count} suscripciones activas. Mira los consejos.',
  subscriptions: 'Mis suscripciones',
  trial: 'Prueba',
  billedToday: 'Se cobra hoy',
  billedTomorrow: 'Se cobra manana',
  billedIn: 'Se cobrara en {days} {label}',
  billingDate: 'Cobro: {date}',
  noSubscriptions: 'Todavia no has agregado suscripciones.',
  addSubscriptionAction: 'Agregar suscripcion',
  manageAction: 'Gestionar suscripcion',
  manageUnavailable: 'No se indico un enlace de suscripcion',
  deleteAction: 'Eliminar',
  deleteConfirmTitle: 'Eliminar suscripcion?',
  deleteConfirmDescription: 'La suscripcion se eliminara de la lista y no se podra recuperar.',
  deleteConfirmSubmit: 'Eliminar',
  searchPlaceholder: 'Buscar...',
  categoryAll: 'Todas las categorias',
  categorySelected: 'Seleccionadas',
  sortLabel: 'Orden',
  sortTerm: 'Por fecha de cobro',
  sortPriceDesc: 'Mas caras primero',
  sortPriceAsc: 'Mas baratas primero',
  sortName: 'Nombre',
};
