import { DashboardIntl } from '../../../core/i18n/translations.model';

export const dashboardIntlRu: DashboardIntl = {
  title: 'Дашборд',
  subtitle: 'Твои подписки под контролем',
  monthly: 'В месяц',
  yearly: 'В год',
  categories: 'Категории',
  topCategory: 'Топ категория',
  score: 'Оценка SubWise',
  scoreText: 'У тебя {count} активных подписок. Загляни в советы.',
  subscriptions: 'Мои подписки',
  trial: 'Пробный период',
  billedToday: 'Спишут сегодня!',
  billedTomorrow: 'Завтра спишут!',
  billedIn: 'Спишут через {days} {label}',
  billingDate: 'Списание: {date}',
  noSubscriptions: 'У тебя пока нет добавленных подписок.',
  addSubscriptionAction: 'Добавить подписку',
  deleteAction: 'Удалить',
  deleteConfirmTitle: 'Удалить подписку?',
  deleteConfirmDescription: 'Подписка будет удалена из списка без возможности восстановления.',
  deleteConfirmSubmit: 'Удалить',
  searchPlaceholder: 'Поиск...',
  categoryAll: 'Все категории',
  categorySelected: 'Выбрано',
  sortLabel: 'Сортировка',
  sortTerm: 'По дате списания',
  sortPriceDesc: 'Сначала дорогие',
  sortPriceAsc: 'Сначала дешёвые',
  sortName: 'По имени',
};
